# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
install:
  - Rscript -e 'install.packages("INLA",repos=c("https://cran.rstudio.com/", INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)'
